const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
function loadPolicy(){let source=fs.readFileSync(path.join(__dirname,'../src/domain/menuWorkflow.ts'),'utf8').replace(/export /g,'').replace(/ as const/g,'').replace(/:any\[\]/g,'').replace(/:any/g,'').replace(/:string/g,'').replace(/new Set<string>/g,'new Set');const module={exports:{}};vm.runInNewContext(`${source}\nmodule.exports={validateOcr,validateMenu,validateLabels,validateTranslation,validateTransition};`,{module,exports:module.exports,Set,Number,Error,Array});return module.exports;}
const p=loadPolicy();
test('low confidence and handwriting enter correction queue',()=>{assert.equal(p.validateOcr({source_checksum:'sha256:x',source_type:'pdf',page_count:2,deskew_angle:3,ocr_confidence:.72,handwriting:true}).manual_correction_required,true);});
test('menu reconstruction rejects duplicates and fractional minor units',()=>{assert.throws(()=>p.validateMenu({currency:'USD',sections:[{name:'Mains',items:[{id:'x',name:'Soup',price:1.001},{id:'x',name:'Salad',price:2}]}]}),/invalid price|duplicate/);});
test('safety labels require versioned external evidence',()=>{assert.throws(()=>p.validateLabels([{type:'allergen',name:'nuts',evidence_ref:'supplier:1',evidence_version:'v1',safety_inferred:true}]),/may not be inferred/);});
test('publication needs authority, provider receipt, and rollback',()=>{assert.throws(()=>p.validateTransition('scheduled','published',{role:'menu_manager'}),/receipt/);assert.equal(p.validateTransition('scheduled','published',{role:'menu_manager',providerReceipt:'r1',rollbackVersion:1}),true);});
test('migration and store enforce tenant idempotency and row locking',()=>{const sql=fs.readFileSync(path.join(__dirname,'../migrations/003_menu_workflow.sql'),'utf8');const store=fs.readFileSync(path.join(__dirname,'../src/domain/menuWorkflowStore.ts'),'utf8');assert.match(sql,/UNIQUE \(tenant_id, idempotency_key\)/);assert.match(sql,/uq_menu_audit_correlation/);assert.match(store,/FOR UPDATE/);});

test('normal decimal menu prices are accepted without floating point rejection',()=>{assert.equal(p.validateMenu({currency:'USD',sections:[{name:'Mains',items:[{id:'a',name:'Dish',price:19.99}]}]}).item_count,1);});
test('blank prices and absent OCR confidence are not zero-value evidence',()=>{assert.throws(()=>p.validateMenu({currency:'USD',sections:[{name:'Mains',items:[{id:'a',name:'Dish',price:null}]}]}));assert.throws(()=>p.validateOcr({source_checksum:'x',source_type:'pdf',page_count:1,deskew_angle:0,ocr_confidence:null}));});
test('independent review compares canonical identities and protects missing names',()=>{assert.throws(()=>p.validateTransition('translation_review','approved',{role:'admin',actorId:'1',createdBy:1,labelEvidenceCount:1,translationReviewed:true}));assert.throws(()=>p.validateTranslation({source:{},target:{},protected_names:['Dish'],locale:'en',currency:'USD',round_trip_score:1}));});
