import { Router, Response } from 'express';
import pool from '../db/connection';
import { authenticateToken, AuthRequest } from '../middleware/auth';
import { validateOcr } from '../domain/menuWorkflow';
import { transitionMenu } from '../domain/menuWorkflowStore';

const router=Router();router.use(authenticateToken);
router.post('/ingestions',async(req:AuthRequest,res:Response)=>{try{const tenantId=String(req.userId);const v=validateOcr(req.body);for(const f of ['ingestion_ref','idempotency_key','object_ref'] as const)if(!req.body[f])return res.status(400).json({error:`${f} is required`});const existing=await pool.query('SELECT * FROM menu_ingestions WHERE tenant_id=$1 AND idempotency_key=$2',[tenantId,req.body.idempotency_key]);if(existing.rows[0]){if(existing.rows[0].source_checksum!==v.source_checksum)return res.status(409).json({error:'idempotency key reused with different source'});return res.json({...existing.rows[0],replayed:true});}const q=await pool.query(`INSERT INTO menu_ingestions(tenant_id,ingestion_ref,idempotency_key,source_type,source_checksum,object_ref,page_count,deskew_angle,ocr_confidence,layout_kind,handwriting,correction_required,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[tenantId,req.body.ingestion_ref,req.body.idempotency_key,req.body.source_type,v.source_checksum,req.body.object_ref,v.page_count,v.deskew_angle,v.ocr_confidence,req.body.layout_kind||null,Boolean(req.body.handwriting),v.manual_correction_required,String(req.userId)]);res.status(201).json(q.rows[0]);}catch(e:any){res.status(400).json({error:e.message});}});
router.get('/menus/:menuRef/versions/:version',async(req:AuthRequest,res:Response)=>{const q=await pool.query('SELECT * FROM menu_versions WHERE tenant_id=$1 AND menu_ref=$2 AND version=$3',[String(req.userId),req.params.menuRef,Number(req.params.version)]);if(!q.rows[0])return res.status(404).json({error:'menu version not found'});res.json(q.rows[0]);});
router.post('/menus/:menuRef/versions/:version/transition',async(req:AuthRequest,res:Response)=>{try{res.json(await transitionMenu({tenantId:String(req.userId),actorId:String(req.userId),role:req.userRole||'viewer',menuRef:req.params.menuRef,version:Number(req.params.version),to:req.body.to,reason:req.body.reason,correlationId:req.body.correlation_id,context:req.body.context||{}}));}catch(e:any){res.status(e.code==='NOT_FOUND'?404:409).json({error:e.message});}});
export default router;
